### ISSUE TITLE
Please tag releases of Helenus

### ISSUE THREAD

**Issue by sunweaver** [simplereach/helenus#106]
Hi,

I am currently preparing for packaging Etherpad lite for Debian and Helenus is a step on the dependency list.

When introspecting your source project I found that there is only one very old tag in the Git project.

For distro packaging, properly made upstream releases ease the package maintainers' days, so my request for Helenus is that you tag the latest release appropriately on this Github project.

And: please also tag future releases of Helenus, so that the Debian QA portal tells the Node.js maintainers in Debian that there is a new version of Helenus to package.

Thanks a lot + Cheers,
Mike (aka sunweaver@debian.org)

**Comment by devdazed** [comment]
Good catch, I haven't been keeping up on this.  Do the debian packages need the github source project?  Because all of the versions are still in NPM.  I tagged the latest version, but I'll have to go through and see where the commit is that got pushed to NPM to tag the previous releases.

**Comment by sunweaver** [comment]
Hi Russ,

for Debian I use the Github sources. NPM is, just like Debian, some other way of distributing your software. Github is considered as upstream, all those distro\* are different downstreams. So taking packages from NPM would be like re-packaging from some other distro/downstream.

Latest release tag is sufficient for me atm. I'd appreciate if you also could tag future releases.

Thanks
Mike

## 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
fon: +49 (1520) 1976148

GnuPG Key ID 0x25771B13
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

----- Original message -----

**Comment by devdazed** [comment]
No problem, thanks. I'll leave this open until I tag the previous versions, for consistency.  I'll also keep up on the new releases.
