### ISSUE TITLE
CQL injection in `Connection.cql()`

### ISSUE THREAD

**Issue by dohse** [simplereach/helenus#11]
When calling `Connection.cql()` like

```
var userControlledInput = "X'='ChoosenValue', 'ChoosenColumnName";
connection.cql("UPDATE MyColumnFamily SET '%s'='MyValue' WHERE KEY='MyKey';", [userControlledInput], cb);
```

the attacker could at least set arbitrary column names and values. I am not yet firm with cql semantics, so i am not providing a patch, but i guess single quotes (and backslashes)  in the arguments needs to be escaped. Even better would be a server-side placeholder semantic.

The conversion from command and arguments to the cql that is sent to the server happens in `connection.js` at:

```
if(args){
  args.unshift(cmd);
  cql = new Buffer(util.format.apply(this, args));
} else {
  cql = new Buffer(cmd);
}
```

**Comment by ctavan** [comment]
Just to add some references, here's the node-cassandra-client-way: https://github.com/racker/node-cassandra-client/blob/master/lib/driver.js#L59-109 (could be done nicer IMO)
And here's some example from node-mysql: https://github.com/felixge/node-mysql/blob/master/lib/client.js#L145-199

Anyhow I really like the `?`-placeholder-style and I've seen it in many places when dealing with SQL-like database-queries (which CQL tries to mimic).

**Comment by ctavan** [comment]
Looks like single quotes have to be escaped by another single quote, see https://issues.apache.org/jira/browse/CASSANDRA-2993

At least we're not in danger of really dangerous CQL injections: http://www.mail-archive.com/user@cassandra.apache.org/msg14907.html

**Comment by devdazed** [comment]
I'll be pushing out a fix to address the vulnerability.  I'll escape the single quote as that is all the official driver is doing.  As for the `?` placeholder way, I see how people can want this, I also see how people would want to use the NodeJS way of doing it.  I think I'll have `?` be synonymous with `%s`. That should allow for use either way.

**Comment by devdazed** [comment]
just fyi, all of this was published under version 0.3.3. including the ability to use a `?` placeholder in cql.

**Comment by JNayak** [comment]
Looks like this fix is in JS file. Can we do it at server code?

**Comment by devdazed** [comment]
I'm not sure what you mean?

**Comment by JNayak** [comment]
Any security fix at client side javascript can be easily bypaased. It would be good if we have this fix on the server side code.

**Comment by devdazed** [comment]
This is for [node.js](http://nodejs.org/), not client side JavaScript.
