### ISSUE TITLE
Pooling flawed, or improper usage?

### ISSUE THREAD

**Issue by asilvas** [simplereach/helenus#112]
Initial load tests yielded surprising results, as my usage of pooling is either flawed, or the pooling logic is flawed. Despite only having the hostPoolSize of 1 (for testing only, normally this would be much higher), across 4 child processes, hitting a 3-server Cassandra cluster (1x4x3=12 connections), what is actually happening is connections go up indefinitely until one side or the other chokes.

It's important to note that this is a web server, so the concurrent requests/sec are in the hundreds, or even thousands. But what I'd expect with a poolSize of only 1 (12 connections across 4 processes and 3 cassandra servers), is that no more than 12 requests at any one time could be served up by Cassandra, causing a wait until the next connection is free. As indicated earlier, the low connections is for testing only to demonstrate the problem I'm seeing, as normally I would allow far higher # of connections.

This is the oversimplified code:

``` javascript
// request comes in
pool.connect(function(err, keyspace) { // expecting connections never to exceed what I allotted
  pool.cql("my query", data, function (err, results) {
    // respond
  });
});
```

After reviewing the helenus code however, I quickly found that this is not how "connect" on the pool works, and instead establishes a FULL set of new connections (12) every time I call "connect"... This seems wrong to me, as it negates the purpose of the "ConnectionPool", but alas I looked at other commands only to find no real solution to this problem. "getConnection" only works if there is already an available connection, but fails otherwise. The only options I'm currently seeing is to create my own custom pool to manage connections myself.

I'm hoping I'm missing something, and that this isn't the intended behavior of the "ConnectionPool".

**Comment by devdazed** [comment]
You're right that you shouldn't be calling connect multiple times.  Do you call `connect` every time for your MySQL or MongoDB connections?  The way this behaves is in line with the usage of other drivers, and shouldn't be unexpected behavior.  It would be unexpected to call `connect` and have it not do any "connecting" at all.

The connection pool is designed to connect to multiple machines multiple times.  This `pool` of connections is used internally by the driver for sending requests to a random connection. `getConnection` is an internal method and is not designed to be used by the application.

The proper way would be to store the pool in a variable and reference it multiple times. Alternatively you can connect and specify the the queries for your routes.

eg.

``` js

function onrequest(req, res){
  pool.cql("my query", data, function (err, results) {
    res.send(results)
  });
}

pool.connect(function(err){
  app.get('/', onrequest);
});
```

Please check out: [Creating your first Node.JS app with Cassandra](http://devdazed.com/2012/12/19/creating-your-first-nodejs-app-with-cassandra/)
and https://github.com/devdazed/node-cassandra-webinar

**Comment by asilvas** [comment]
Your example is perfect, and I completely agree that is how it should work. In fact, my original implementation was exactly that.

However, simply invoking .cql (which calls getConnection) will fail if all connections are in use (which will be common under load), rather than executing once a connection is available. Having no way to know when a pooled connection is available again, I would be left with either ugly retry logic (even FIFO retry logic) or simply failing the entire request.

There's got to be a better way?

**Comment by devdazed** [comment]
using `.cql` under load should not fail if all connections are in use.  Do you have any error information around this?  Maybe a more full featured example that I can throw apache bench at.

**Comment by mreiferson** [comment]
arguably that should be an error (exhausting your connection pool)... you want back pressure, not an internal queue (and if you _do_ _really_ want to queue, thats probably outside the scope of this library anyway)

**Comment by devdazed** [comment]
That's not really how NodeJS is designed to work.  It will internally queue up requests as everything is async. I would need to put in a serious hack to attempt to prevent use of a connection while it is waiting on a response.

**Comment by asilvas** [comment]
Reverted my code to use the pattern you described above, and while it "works", it still establishes TONS of connections under load, rather than reusing connections. I only call "connect" once.

A quick "netstat -n" shows tens of thousands of connections in TIME_WAIT.

The sequence goes:

1) Start service
2) pool.connect
3) Connected
4) Idle - Verify only 12 connections via netstat
5) Start load test
6) Stop after ~60 seconds
7) Tens of thousands shown on netstat

Is this is the intended behavior, despite using a poolSize of 1 (per process)? I'm basically ddosing our cassandra cluster.

**Comment by devdazed** [comment]
interesting. i have had a similar issue with http in the past.  I will look into this.

**Comment by asilvas** [comment]
Thanks much. Let me know if I can help.

**Comment by devdazed** [comment]
I will be out of the country for 2 weeks, if you could put together a working stress test that shows this, I can have someone on my team take a look.

**Comment by asilvas** [comment]
Will do.

**Comment by asilvas** [comment]
Working through the load test script, I identified the culprit in my code (unrelated to your library!). I'll close, but here's a very handy load test code snippet in case anyone is interested. Thanks for your help!

``` javascript
var
    helenus = require("helenus"),
    cluster = require("cluster")
;

var dummyClients = parseInt(process.argv[2]) || 100;
var workerProcesses = parseInt(process.argv[3]) || 2;
var poolConfig = {
    "hosts": ["server1:9160","server2:9160","server3:9160"],
    "keyspace": "{keyspace}",
    "user": "{username}",
    "password": "{password}",
    "timeout": 4000,
    "cqlVersion" : "3.0.0",
    "consistencyLevel": helenus.ConsistencyLevel.ONE,
    "hostPoolSize": 10
};
var cqlQuery = "SELECT * FROM someTable LIMIT 1";
var pool = new helenus.ConnectionPool(poolConfig);
var startTime;
var ops = 0;
var errs = 0;

function DummyClient() {

    pool.cql(cqlQuery, [], function (err, results) {
        // don't care about results, it either worked or it didn't
        if (err) {
            errs++;
        } else {
            ops++;
        }

        DummyClient();
    });

}

if (cluster.isMaster) {
    console.log("Spawning " + workerProcesses + " worker processes to do my bidding!");
    for (var i = 0; i < workerProcesses; i++) {
        cluster.fork();
    }
} else {
    pool.connect(function() {

        // assume success for load test. spin up all dummy clients

        for (var i = 0; i < dummyClients; i++) {
            DummyClient();
        }

        console.log(dummyClients + " dummy clients spun up...");

        startTime = new Date().getTime();

        tickTock();
    });
}

function tickTock() {
    setInterval(function() {
        console.log("IOPS: " + ops + ", errors: " + errs);

        startTime = new Date().getTime();
        ops = 0;
        errs = 0;
    }, 1000);
}
```

**Comment by devdazed** [comment]
Thanks!
