### ISSUE TITLE
ConnectionPool.close should take a callback

### ISSUE THREAD

**Issue by jaredhirsch** [simplereach/helenus#114]
`Pool.connect` takes a callback, `Pool.close` doesn't--instead it emits a signal. This strikes me as a bit counterintuitive--is there any particular reason `close` was implemented in this way?

**Comment by devdazed** [comment]
I think originally my idea was to emit close in the event the connection was force closed, allowing the user to do something with it.  I'm not opposed to having a callback as well, I assume that putting the callback directly after the emit would be the place to put it. For consistency sake, we should probably also emit `connect` once connected.
