### ISSUE TITLE
Adding support for removing multiple columns

### ISSUE THREAD

**Issue by muirmanders** [simplereach/helenus#120]
I'm adding support to the thrift interface for deleting multiple columns at once (batched), but I had a question I would like to get your input on first. Since the existing remove function supports composite columns, using an array to pass multiple columns to "remove" would be ambiguous. I see my options as adding a separate "remove_multi" method that takes an array of columns, or specifying multiple columns to "remove" as additional arguments before the callback. What are your thoughts on this?

**Comment by devdazed** [comment]
would it work if it is an array, but if the value in the array is an array then we treat it as composite?

**Comment by muirmanders** [comment]
I don't think that would work. A simple example would be deleting the column ['foo', 'bar']. You can't know if it is a composite column or two separate columns. The existing interface treats that as a composite, so that has to be maintained (i.e. you can't require callers to always wrap their columns in an outer array).

**Comment by devdazed** [comment]
I meant it would be something like deleting the column `[ ['foo','bar'] ]` if the column family is a composite type and a flat array if the column family isn't a composite type.

**Comment by muirmanders** [comment]
Yes, that makes sense, but it would break the existing interface for deleting composite columns.

**Comment by devdazed** [comment]
hmm, this might be why I haven't added it yet ;)

**Comment by psanford** [comment]
I prefer remove_multi b/c I think it will be more obvious how to use the api correctly.

**Comment by devdazed** [comment]
sure, also if I ever get around to implementing a multiget, this will set a standard for how multi-\* things are done
