### ISSUE TITLE
Thrift column family issue.

### ISSUE THREAD

**Issue by AndrewRademacher** [simplereach/helenus#137]
I'm attempting to use the Thrift components in the helenus driver in conjunction with the Cassandra tutorial for data modeling.  When calling get on a keyspace to find a given table an error is thrown that the column family doesn't exist, even when performing operations on the column family via CQL works just fine.

``` javascript
var _ = require('underscore'),
    helenus = require('helenus'),
    pool = new helenus.ConnectionPool({
        hosts: ['localhost:9160'],
        keyspace: 'musicdb',
        timeout: 3000
    });

pool.connect(function(err, keyspace) {
    if (err) return console.error(err);

    // Failed attempt to retrieve the table/columnfamily with thrift.
    keyspace.get('playlists', function(err, playlists) {
        if (err) return console.error(err);
        console.log(playlists);
    });

    // Successful call to the playlists table with CQL.
    pool.cql('SELECT * FROM playlists', function(err, rows) {
        if (err) return console.error(err);

        _.each(rows, function(row) {
            console.log(row.get('album').value);
        });
    });
});
```

The error from calling with thrift is...

```
{ [HelenusNotFoundError: ColumnFamily playlists Not Found] name: 'HelenusNotFoundError' }
```

I'm completely new to this driver package, so it could be that I'm just calling it incorrectly.

**Comment by mrvisser** [comment]
I can't test at the moment but I'm pretty sure if you created the column family with CQL3 then you won't be able to query it with thrift or CQL2.

If you want to play with thrift you'll want to either create the column family with the thrift API or by using CQL with the connection in cqlVersion=2 mode.

**Comment by mrvisser** [comment]
Worth mentioning that when using CQL3 if you create with the "WITH COMPACT STORAGE" descriptor then that should also be thrift-compatible.

**Comment by AndrewRademacher** [comment]
The CQL3 issue was it.  I created the table using cqlsh running CQL version 3.1.1.  Is thrift planned to be compatible with CQL 3, or should I assume that Thrift is a deprecated pattern going forward?

**Comment by mrvisser** [comment]
From what the Cassandra community has said thrift will always be supported but don't expect any bells and whistles added to it moving forward. New query and indexing features are all being added to CQL3 and its new underlying storage structure.

**Comment by AndrewRademacher** [comment]
Alright, I appreciate the assist.
