### ISSUE TITLE
Add support for prepared CQL queries

### ISSUE THREAD

**Issue by ctavan** [simplereach/helenus#16]
Cassandra 1.1 adds support for prepared CQL queries. These should be supported by helenus as well.

The underlying thrift calls are:

``` javascript
CassandraClient.prototype.prepare_cql_query = function(query, compression, callback) {}
CassandraClient.prototype.execute_prepared_cql_query = function(itemId, values, callback) {}
```

If nobody else has already looked into that I'll try to provide a patch soonish.

**Comment by devdazed** [comment]
How do the prepared cql queries work?  Is the preparation stored server side? or is it a client side preparation.  Also, how long is the prep good for, is it per connection or permanent?

**Comment by ctavan** [comment]
Preparations are stored serverside.

I still have to figure out if they survive connections. If not, we'll have to keep track on which connections of the pool a statement has already been prepared. It's probably best to have a look at http://code.google.com/a/apache-extras.org/p/cassandra-jdbc/

https://issues.apache.org/jira/browse/CASSANDRA-2475 has some more info but no definite answer whether prepared cql queries survive connections.

**Comment by ctavan** [comment]
The latest python cql driver also has support for prepared statements: http://pypi.python.org/pypi/cql/

**Comment by ctavan** [comment]
I'm actually working on this but it seems a bit more complicated than I thought...

**Comment by devdazed** [comment]
Would you like me to push it out to a later milestone?

**Comment by ctavan** [comment]
Yeah, I think 0.8 would be more realistic, thanks.

CQL 3 is beta in Cassandra 1.1 anyways and 1.1.0 is not even released yet, so I think it's quite ok to have only partial CQL3 support for now.
