### ISSUE TITLE
Global Variable leak errno

### ISSUE THREAD

**Issue by devdazed** [simplereach/helenus#20]
the tests are reporting a global variable leak of the variable `errno` coming from the `thift.js` test file.

**Comment by devdazed** [comment]
The value of `errno` when leaked is `EOF`

**Comment by ctavan** [comment]
This is a true mystery to me. Where does this variable even come from?

**Comment by devdazed** [comment]
i have no idea, i've grepped the entire directory for it and it just doesn't exist, it may be made dynamically somewhere.  I know its not just my box because travis-ci also reports the leak.

**Comment by devdazed** [comment]
ok, the leak is apparent after the connection emits close:

``` javascript
  var helenus = require('helenus'),
      pool = new helenus.ConnectionPool({
        hosts      : ['localhost:9160'],
        keyspace   : 'test',
        timeout    : 3000
      });
  console.log('base-errno:', global.errno);

  pool.on('error', function(err){
    console.error(err.name, err.message);
    console.log('error-errno:', global.errno)
  });

  pool.on('close', function(){
    console.log('close-errno:', global.errno)
  });

  pool.connect(function(err, keyspace){
    if(err){
      throw(err);
    }
    console.log('connect-errno:', global.errno)

    keyspace.get('issue_20', function(err, cf){
      if(err){
        throw(err);
      }
      console.log('keyspace-errno:', global.errno)

      cf.insert('foo', {'bar':'baz'}, function(err){
        if(err){
          throw(err);
        }
        console.log('insert-errno:', global.errno)

        cf.get('foo', function(err, row){
          if(err){
            throw(err);
          }

          row.get('bar').value // => baz

          console.log('get-errno:', global.errno)

          pool.close()
        });
      });
    });
  });
```

**Comment by devdazed** [comment]
Ok, I found the issue.  It is actually a bug in the `net` module of node.  I submitted an issue joyent/node#3095, so i will close this one.

**Comment by devdazed** [comment]
As a side note, the only reason we haven't seen this before is that we never have opened and closed multiple connections until the new tests were written. So this problem has always existed, just never seen.

**Comment by ctavan** [comment]
Good to know! I've seen that a couple of times already but never dug so deep.
