### ISSUE TITLE
Allow multiple connections per host

### ISSUE THREAD

**Issue by devdazed** [simplereach/helenus#21]
We should probably allow mulitple connections per host.  I'm open to ideas on implementation. What I had in mind was a parameter on ConnectionPool like `connections_per_node`, that will tell the pool to open up N connections to each node.  This may provide a performance increase and resiliency in high volume applications.

**Comment by ctavan** [comment]
Ok, but I vote for `connectionsPerNode`...

**Comment by dokipen** [comment]
+1

**Comment by dokipen** [comment]
https://github.com/appsattic/oibackoff/ might be useful to us.

**Comment by devdazed** [comment]
Closed with #70
