### ISSUE TITLE
How to handle IntegerType and DecimalType

### ISSUE THREAD

**Issue by ctavan** [simplereach/helenus#22]
Cassandra's IntegerType is implemented as arbitrary precision Java BigIntegers and DecimalType is implemented as arbitrary precision Java BigDecimals, see the documentation and the marshallers from the cassandra source:
- [Data types in the docs](http://www.datastax.com/docs/1.0/ddl/column_family#about-data-types-comparators-and-validators)
- [IntegerType](https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/db/marshal/IntegerType.java#L20)
- [Decimal Type](https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/db/marshal/DecimalType.java#L20)

How should this be handled in the node driver? For now (since I haven't had a use case yet) I'm ok with just using javascript numbers, but maybe we'll have to switch to something like [node-bigint](https://github.com/substack/node-bigint) at some point? What do you thing?

**Comment by devdazed** [comment]
i was also thinking node-bigint is the way to go, however, that would require a compiled dependency and the target installation location have gmp installed on it.  What do you think?

**Comment by ctavan** [comment]
The binary dependency is the reason why I don't really like the node-bigint idea. There are pure-js alternatives (like the one used by node-cassandra-client) but they also kind of suck...

My suggestion is to just leave this ticket open until somebody comes up with an actual use case for arbitrary precision numbers and then see what would work best.

**Comment by ctavan** [comment]
Or maybe https://github.com/eschnou/node-bignumber

**Comment by devdazed** [comment]
I'm not sure about that one.  Its a direct port from a browser version and it doesn't have any tests.  Furthermore, the last time it had anything doen to it was over a year ago.

**Comment by simpleseeker** [comment]
When I pull very large Ints (64bit), I loss precision. Because I have to work with large values, I'm already working with node-bigint.  These are lookup UIDs, which causes havac for me. Being able to retrieve large Ints without lossing precision will make a lot of problems go away.

**Comment by duyleekun** [comment]
https://github.com/justmoon/node-bignum doesn't required compiled dependency

**Comment by devdazed** [comment]
how do you figure?  `bignum.cc` is in the root and the install script is `"node-gyp configure build"`.  More than likely I'll be working in this, or [node-num](https://github.com/shtylman/node-num) which is a pure JS version.
