### ISSUE TITLE
Update Testing Framework

### ISSUE THREAD

**Issue by devdazed** [simplereach/helenus#24]
The current testing framework is using whiskey, the once problem is that setup and teardowns need to be in the test file.  This is making the test files get out of hand.  I recommend going to [Mocha](http://visionmedia.github.com/mocha/), the only requirement that I have is that is is not BDD and the it supports code coverage.

**Comment by ctavan** [comment]
I think another important requirement should be that the existing tests work with only minor code changes. Or do you want to rewrite everything?

**Comment by devdazed** [comment]
I'm not sure, the test are all fairly simple so a rewrite wouldn't be such a bad thing.
