### ISSUE TITLE
Add Support for SuperColumns

### ISSUE THREAD

**Issue by devdazed** [simplereach/helenus#29]
Even though it is considered bad practice, we should probably fully support SuperColumns

**Comment by ctavan** [comment]
I'm totally against that! AFAIK SuperColumns have already been replaced by CompositeColumns internally and use of them is strongly discouraged. If I got the cassandra core developers right the only reason they still exist is that the thrift api is promised to remain backwards compatible.

Unless somebody who wants to use SuperColumns with the helenus-driver presents a good reason why has to do it, I think we should not support it.

**Comment by devdazed** [comment]
I was thinking more along the lines of they already have SuperColumns and the want to run node with Helenus in their environment.  Does CQL3 Support SuperColumns?

**Comment by ctavan** [comment]
Nope. CQL3 has composite columns only.

**Comment by devdazed** [comment]
Very well.  Lets remove completely the concept of SuperColumns and emit an error if we come across a SuperColumnFamily.  I would rather have hardened support for composites than half supporting both.

**Comment by devdazed** [comment]
We should probably open an issue to remove support for SuperColumns
