### ISSUE TITLE
Give the user ability to change underlying marshaller

### ISSUE THREAD

**Issue by devdazed** [simplereach/helenus#3]
The user should be able to let the driver know what type of marshaller to use when storing data on the thrift side of the driver.  This should override what the schema says.

**Comment by elubow** [comment]
It would be great if this could work similar to the Pycassa driver.  For instance, if the schema for the CF has a default validator of UTF8Type() and you want to make a single column (composite in this case) a boolean value, the driver should have the ability to force Cassandra to ignore it's default column family validator:

``` python
from pycassa.types import BooleanType
...
column_family.column_validators[('foo', 'bar')] = BooleanType()
columns[('foo','bar')] = True
column_family.insert(row_key,columns)
```

**Comment by devdazed** [comment]
This will be done in the following manner:

``` js
columnFamily.setColumnValidator(['foo','bar'], 'BooleanType');
```

or

``` js
columnFamily.setColumnValidator(['foo','bar'], 'CompositeType(BytesType, LongType)';
```

for composites

**Comment by devdazed** [comment]
Added with 1191611cede60eeae8adced44474ed295590f87d
