### ISSUE TITLE
Use debian packages for CI

### ISSUE THREAD

**Issue by ctavan** [simplereach/helenus#38]
I'd suggest using the debian packages from http://www.apache.org/dist/cassandra/debian/pool/main/c/cassandra/ for CI.

They run smoothly under ubuntu and they will put all output to `/var/log/cassandra/` so it won't mix up with the actual test output. If we're interested in the cassandra output for debugging purposes we can still `cat` the log files after the test suite has run.

**Comment by devdazed** [comment]
i dont typically run ubuntu, do you know how to install from a deb off hand?

**Comment by elubow** [comment]
`dpkg -i $pkg_name` or use either `aptitude` or `apt-get install $pkg_name`.

**Comment by devdazed** [comment]
cassandra doesn't have something in apt that I found.  so i just download the package and use `dpkg -i` on it?

**Comment by ctavan** [comment]
Don't worry, I'll provide a patch.

**Comment by ctavan** [comment]
I've made a pull request #40

**Comment by devdazed** [comment]
@ctavan Do you have any idea why the Travis CI build just keeps running and never exits with green?  if you look in both you build as well as ours: http://travis-ci.org/#!/simplereach/helenus, it shows all of them as still building.

**Comment by ctavan** [comment]
Strange thing. Apparently we have to stop cassandra after running the tests to make travis believe that the build has finished. See #41.
