### ISSUE TITLE
Additional fields in `pool.cql()` gets concatenated to cql statement

### ISSUE THREAD

**Issue by dohse** [simplereach/helenus#39]
Running

```
pool.cql("UPDATE KeyValue SET value='?' WHERE key='?'", [value, key, 'additional field'], cb)
```

leads to a cql error, because `'additional field'` gets concatenated to the cql statement by `util.format()`

**Comment by devdazed** [comment]
That's because you have only 2 placeholders

That being said,
I'm not sure what the desired behavior should be.  If we just drop the leftovers, or concatenate.   What are other drivers doing?

**Comment by dohse** [comment]
Am 16. April 2012 17:06 schrieb Russ Bradberry
reply@reply.github.com:

> That's because you have only 2 placeholders
> yes. the additional fields should either be ignored or an error should be given.

**Comment by devdazed** [comment]
So, mysql gives an error. `Error: too many parameters given` and others seem to be ignoring the extras.  I'll slate this for `0.5`

**Comment by dohse** [comment]
Something analog should happen if too few parameters are given
