### ISSUE TITLE
insert timestamp

### ISSUE THREAD

**Issue by Philmod** [simplereach/helenus#4]
Hi, 

When I do "cf.insert('foo', {'bar':'baz'}, function(err){})", the timestamp linked to this column is undefined (1970-01-16 10:43:07.898).

Why doesn't it the actual time?

Regards,
Philippe

**Comment by devdazed** [comment]
Hi,
I am having trouble reproducing this. What version of Cassandra are you running?  What is your ColumnFamily Definition?

**Comment by Philmod** [comment]
Hi!

I'm using the last version (1.0.8) of Cassandra.

cf.insert(rowKey, column, function(err){} );
where column = { 123456789: 12.456 }

The CF is created via helenus as well: 
keyspace.createColumnFamily('CF_name_test', function(err) {} )

Best,
Philippe

**Comment by Philmod** [comment]
Hi, 

I suppose I did something wrong if you closed the issue, can you please explain me what?

Thanks a lot,
Philippe

**Comment by devdazed** [comment]
You didn't do anything wrong.  I fixed the issue, see the commit referenced above.  The fixed version has been published under version 0.3.1

**Comment by Philmod** [comment]
It works great, thanks!
