### ISSUE TITLE
make cql result count equal to number of actual row returned

### ISSUE THREAD

**Issue by samal** [simplereach/helenus#44]
CQL select  return result of  1 even if row is not present, this is due to KEY returned from cql request.
It would be nice if we make result transparent to number of rows returned ie considering only row which has column in it.

https://github.com/simplereach/helenus/blob/master/lib/connection.js#L444
#### Row with no cloumn

res.rows.length=1;
{ key: 'samal1@example.com',
  columns:
   [ { name: 'KEY',
       value: 'samal1@example.com',
       timestamp: 18446744073709552000,
       ttl: null } ] }
#### Cql result

  Row: Key: 'samal1@example.com', ColumnCount: 0, Columns: [ '' ] 
#### Row with column returned.

res.rows.length=1;

 { key: 'samal@example.com',
  columns:
   [ { name: 'KEY',
       value: 'samal@example.com',
       timestamp: 18446744073709552000,
       ttl: null },
     { name: '_uid',
       value: 'da394c47-8ef7-11e1-ba7f-bbdb9a24f338',
       timestamp: 1335373096718000,
       ttl: null },
     { name: 'email',
       value: 'samal@example.com',
       timestamp: 1335373096718001,
       ttl: null },
     { name: 'password',
       value: '40bd001563085fc35165329ea1ff5c5ecbdbbeef',
       timestamp: 1335373096718003,
       ttl: null },
     { name: 'verified',
       value: '0',
       timestamp: 1335374968062000,
       ttl: null },
     ] }

**Comment by devdazed** [comment]
so how would it work if someone was to try to run a range query in CQL where they key exists but there are no columns in that range?  it might be misleading to show the user 0 rows when what they really want to know is 0 columns.  

im interested to hear how other feel about this

**Comment by samal** [comment]
So what you are saying, for range query  100 < X < 200  in row, 
if there is no X value in that range, but key exist. It will return Row=>1, Column=>0 make sense.  
But then how to differentiate between Key actually present and not present.

On the other and, if column has TTL or being deleted, eventually key (compaction) will be deleted for zero columns. While inserting if key is present it will use it, otherwise create it so here no conflict in key occurs. 

What we are really looking for, is columns, not row, it will make sense to return zero row, if no column or no range column present.

**Comment by devdazed** [comment]
So, in the latest version of C\* (1.1.1) and CQL 3, this problem no longer exists because range ghosts are removed.
