### ISSUE TITLE
Double quote escaping for placeholder substitution

### ISSUE THREAD

**Issue by rmechler-sencha** [simplereach/helenus#45]
I'm trying to store a column value that contains double quotes, by substituting a placeholder using a string, e.g., 

```
  var data = '{username: "bob"}';
  pool.cql("INSERT INTO MyColumnFamily (id, data) VALUES ('1', %s)", [data], function(err){
      ...
```

the value that ends up being stored is this:

```
cqlsh:keyspace1> select * from MyColumnFamily where id = '1';
 id | data
----+-----------------------
 1 | {username: \\"bob\\"}
```

when what I really want is this:

```
cqlsh:keyspace1> select * from MyColumnFamily where id = '1';
 id | data
----+-----------------------
 1 | {username: "bob"}
```

there doesn't seem to be any way around this, unless I specify the value directly in the query (no substitution). 

Might be related to issue #36

**Comment by devdazed** [comment]
This fix was just published under 0.5.2
