### ISSUE TITLE
Connection pool reconnect does not set CQL version

### ISSUE THREAD

**Issue by rmechler-sencha** [simplereach/helenus#49]
I have cqlVersion : '3.0.0' set for my pool. I take my C\* server down and bring it back up, and a new connection is established, initiated by checkDead(). However, the connect() function used for this does not set the cqlVersion (and so subsequent queries fail). The patch below will fix the problem, however, there might be a better fix that reuses the code for creating connections.

```
--- helenus.orig/lib/pool.js    2012-05-14 10:43:47.000000000 -0700
+++ helenus/lib/pool.js 2012-05-14 10:45:34.000000000 -0700
@@ -234,7 +234,8 @@ Pool.prototype.monitorConnections = func
       keyspace: self.keyspace,
       user: self.user,
       password: self.password,
-      timeout: self.timeout
+      timeout: self.timeout,
+      cqlVersion: self.cqlVersion
     });

     connection.on('error', function(err){
```

**Comment by devdazed** [comment]
This fix was published under version 0.5.3
