### ISSUE TITLE
Allow expiration (ttl) times when setting column values

### ISSUE THREAD

**Issue by calvinfo** [simplereach/helenus#51]
I'd like to be able to set values with an expiration, similar to the way that the java or python clients work.

Something like:

```
 cf.insert('foo', { bar : 'baz' }, { ttl : 4000 }, callback);
```

**Comment by devdazed** [comment]
so all columns you specify in this query will have the same ttl?

**Comment by calvinfo** [comment]
Right, I'm looking for something similar to pycassa's ttl keyword (see the third line of the first example here):

http://pycassa.github.com/pycassa/api/pycassa/batch.html#module-pycassa.batch

Astyanax does this on a per column basis, which could also work. I mainly just want some way to expire keys from helenus.
