### ISSUE TITLE
Make sure no-longre-returned ghosts are handled correctly.

### ISSUE THREAD

**Issue by ctavan** [simplereach/helenus#53]
With 1.1.1 CQL-queries don't return range ghosts any more, see https://issues.apache.org/jira/browse/CASSANDRA-3982

Probably we'll have to change the tests accordingly: https://github.com/simplereach/helenus/blob/master/test/cql3.js#L100-125

**Comment by devdazed** [comment]
closed this, just going to check with the latest version of C*. as that is the version they recommend. we will probably need to document that the tests will fail on 1.1.0 with cql3
