### ISSUE TITLE
Tests fail on master

### ISSUE THREAD

**Issue by dokipen** [simplereach/helenus#55]
Could it be my cassandra.yaml? Looks like the delete test case is expecting "ghosts" but on my instance it is deleted appropriately.

I'm not sure why the bad user input test would be expected to pass. The single-quote is escaped to create the query:

SELECT foo FROM cql_test WHERE id='''foobar'

There is no row with that ID so it should be expected to return zero rows.

Let me know and I can fix these tests and submit a patch.

12:02:07 [doki_pen@nyan ~/src/helenus][master]$ npm test

> helenus@0.5.3 test /home/doki_pen/src/helenus
> make test

NODE_PATH=lib/ node_modules/whiskey/bin/whiskey --real-time --scope-leaks --tests "test/units.js test/cql3.js test/cql2.js test/thrift.js"
/home/doki_pen/src/helenus/test/units.js
  setUp                                                                      [OK]
  test uuid library                                                          [OK]
/home/doki_pen/src/helenus/test/cql3.js
  setUp                                                                      [OK]
  test cql create keyspace                                                   [OK]
  test cql use keyspace                                                      [OK]
  test cql static CF create column family                                    [OK]
  test cql static CF update                                                  [OK]
  test cql static CF update with no callback                                 [OK]
  test cql static CF select                                                  [OK]
  test cql static CF select with bad user input                            [FAIL]

Exception
AssertionError: false == true
    at Object.ok (/home/doki_pen/src/helenus/node_modules/whiskey/lib/assert.js:333:29)
    at /home/doki_pen/src/helenus/test/cql3.js:72:12
    at /home/doki_pen/src/helenus/test/cql3.js:14:7
    at onReturn (/home/doki_pen/src/helenus/lib/connection.js:435:7)
    at onReturn (/home/doki_pen/src/helenus/lib/connection.js:370:7)
    at /home/doki_pen/src/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:80:11
    at Object.recv_execute_cql_query (/home/doki_pen/src/helenus/lib/cassandra/Cassandra.js:6968:12)
    at /home/doki_pen/src/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:83:36
    at Socket.<anonymous> (/home/doki_pen/src/helenus/node_modules/helenus-thrift/lib/thrift/transport.js:70:9)
    at Socket.emit (events.js:67:17)

  test cql static CF count                                                   [OK]
  test cql static CF error                                                   [OK]
  test cql static CF count with gzip                                         [OK]
  test cql static CF delete                                                [FAIL]

Exception
AssertionError: 0 === 1
    at Object.strictEqual (/home/doki_pen/src/helenus/node_modules/whiskey/lib/assert.js:333:29)
    at /home/doki_pen/src/helenus/test/cql3.js:116:16
    at onReturn (/home/doki_pen/src/helenus/lib/connection.js:435:7)
    at onReturn (/home/doki_pen/src/helenus/lib/connection.js:370:7)
    at /home/doki_pen/src/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:80:11
    at Object.recv_execute_cql_query (/home/doki_pen/src/helenus/lib/cassandra/Cassandra.js:6968:12)
    at /home/doki_pen/src/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:83:36
    at Socket.<anonymous> (/home/doki_pen/src/helenus/node_modules/helenus-thrift/lib/thrift/transport.js:70:9)
    at Socket.emit (events.js:67:17)
    at TCP.onread (net.js:367:14)

  test cql static CF drop static column family                               [OK]
  test cql dynamic CF create column family                                   [OK]
  test cql dynamic CF update 1                                               [OK]
  test cql dynamic CF update 2                                               [OK]
  test cql dynamic CF update 3                                               [OK]
  test cql dynamic CF select by row                                          [OK]
  test cql dynamic CF by row and column                                      [OK]
  test cql dense composite CF create column family                           [OK]
  test cql dense composite CF update 1                                       [OK]
  test cql dense composite CF update 2                                       [OK]
  test cql dense composite CF update 3                                       [OK]
  test cql dense composite CF select by row                                  [OK]
  test cql dense composite CF by row and column                              [OK]
  test cql sparse composite CF create column family                          [OK]
  test cql sparse composite CF update 1                                      [OK]
  test cql sparse composite CF update 2                                      [OK]
  test cql sparse composite CF update 3                                      [OK]
  test cql sparse composite CF select by row                                 [OK]
  test cql sparse composite CF by row and column                             [OK]
  test cql drop keyspace                                                     [OK]
  tearDown                                                                   [OK]
/home/doki_pen/src/helenus/test/cql2.js
  setUp                                                                      [OK]
  test cql create keyspace                                                   [OK]
  test cql use keyspace                                                      [OK]
  test cql create column family                                              [OK]
  test cql update                                                            [OK]
  test cql update with no callback                                           [OK]
  test cql select                                                            [OK]
  test cql select with bad user input                                        [OK]
  test cql count                                                             [OK]
  test cql error                                                             [OK]
  test cql count with gzip                                                   [OK]
  test cql delete                                                            [OK]
  test cql drop column family                                                [OK]
  test cql drop keyspace                                                     [OK]
  test too many cql params                                                   [OK]
  test too few cql params                                                    [OK]
  tearDown                                                                   [OK]
/home/doki_pen/src/helenus/test/thrift.js
  setUp                                                                      [OK]
  test pool.connect without keyspace                                         [OK]
  test pool.close without keyspace                                           [OK]
  test pool.connect with keyspace                                            [OK]
  test pool.createKeyspace                                                   [OK]
  test pool.use                                                              [OK]
  test keyspace.createColumnFamily                                           [OK]
  test keyspace.createColumnFamily with composite type                       [OK]
  test keyspace.createSuperColumnFamily                                      [OK]
  test keyspace.get                                                          [OK]
  test keyspace.get composite                                                [OK]
  test keyspace.get supercolumn                                              [OK]
  test keyspace.get from cache                                               [OK]
  test keyspace.get from index                                               [OK]
  test keyspace.get invalid cf                                               [OK]
  test standard cf.insert                                                    [OK]
  test standard cf.insert into composite cf                                  [OK]
  test standard cf.get                                                       [OK]
  test standard cf.get for composite column family                           [OK]
  test standard cf.get with options                                          [OK]
  test standard cf.get with columns names                                    [OK]
  test composite cf.get with columns names                                   [OK]
  test standard cf.get with error                                            [OK]
  test standard cf with Index                                                [OK]
  test standard cf with BytestType                                           [OK]
  test standard cf with LongType                                             [OK]
  test standard cf with IntegerType                                          [OK]
  test standard cf with UTF8Type                                             [OK]
  test standard cf with AsciiType                                            [OK]
  test standard cf with LexicalUUIDType                                      [OK]
  test standard cf with TimeUUIDType                                         [OK]
  test standard cf with FloatType                                            [OK]
  test standard cf with DoubleType                                           [OK]
  test standard cf with DateType                                             [OK]
  test standard cf with BooleanType                                          [OK]
  test standard cf with UUIDType                                             [OK]
  test row.nameSlice                                                         [OK]
  test row.slice                                                             [OK]
  test row.toString and row.inspect                                          [OK]
  test row.forEach                                                           [OK]
  test standard cf remove column                                             [OK]
  test standard cf remove row                                                [OK]
  test standard cf truncate                                                  [OK]
  test keyspace.dropColumnFamily                                             [OK]
  test pool.dropKeyspace                                                     [OK]
  test pool.close                                                            [OK]
##   tearDown                                                                   [OK]

Ran 99 tests in 9.566s

Successes: 97
Failures: 2
Timeouts: 0
Skipped: 0

FAILED

Leaked Variables

  units.js: no leaks detected
  cql3.js: errno
  cql2.js: errno
  thrift.js: errno
make: **\* [test] Error 2

npm ERR! helenus@0.5.3 test: `make test`
npm ERR! `sh "-c" "make test"` failed with 2
npm ERR! 
npm ERR! Failed at the helenus@0.5.3 test script.
npm ERR! This is most likely a problem with the helenus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make test
npm ERR! You can get their info via:
npm ERR!     npm owner ls helenus
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 3.3.8-1-ARCH
npm ERR! command "node" "/home/doki_pen/nvm/v0.6.18/bin/npm" "test"
npm ERR! cwd /home/doki_pen/src/helenus
npm ERR! node -v v0.6.18
npm ERR! npm -v 1.1.21
npm ERR! code ELIFECYCLE
npm ERR! message helenus@0.5.3 test: `make test`
npm ERR! message `sh "-c" "make test"` failed with 2
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/doki_pen/src/helenus/npm-debug.log
npm not ok

**Comment by devdazed** [comment]
We are aware, of this in 1.1.1 and CQL 3, the ghosts are removed in the CQL response, so we need to alter the tests to detect the proper version so that we can ensure that ghosts get check if needed.

**Comment by dokipen** [comment]
I don't think it's possible to get the version of cassandra you are using. Maybe it's just better to test against the latest version.
