### ISSUE TITLE
Can't SELECT (CQL)

### ISSUE THREAD

**Issue by Philmod** [simplereach/helenus#6]
Hi, 

When I try to SELECT like this : 

pool.cql("SELECT \* FROM '%s' WHERE KEY = '%s'", ['cfTest','rowTest'], function(err, results){
      console.log('CQL RESULTS : ');
      console.log(err, results);
    }); 

I get this error : 
HelenusInvalidRequestException: cannot parse 'rowTest' as hew bytes.

Thank you,
Phil

**Comment by devdazed** [comment]
this may be because you have your CF set up with a key_validation_class that is not UTF8Type or ASCIIType. More likely it is probably BytesType.  When using CQL, the entire CQL string is sent over to the C\* servers.  There is not type conversion happening like in the Thrift client.  So if your CF is expecting BytesType (which is represented in hex) then it will return back with the error.  To fix you can either update your CF schema to make the key_validation_class a UTF8Type or ASCIIType, or do the hex conversion yourself like:

```
var row = new Buffer('rowTest').toString('hex');
pool.cql("SELECT * FROM '%s' WHERE KEY = '%s'", ['cfTest',row], function(err, results){
  console.log('CQL RESULTS : ');
  console.log(err, results);
});
```

**Comment by Philmod** [comment]
Ok thanks!

Is it better to storer in BytesType than the others?

Best,
Philippe

------Message d'origine------
De: Russ Bradberry
À: Philippe Modard
Objet: Re: [helenus] Can't SELECT (CQL) (#6)
Envoyé: 9 mars 2012 16:01

this may be because you have your CF set up with a key_validation_class that is not UTF8Type or ASCIIType. More likely it is probably BytesType.  When using CQL, the entire CQL string is sent over to the C\* servers.  There is not type conversion happening like in the Thrift client.  So if your CF is expecting BytesType (which is represented in hex) then it will return back with the error.  To fix you can either update your CF schema to make the key_validation_class a UTF8Type or ASCIIType, or do the hex conversion yourself like:

```
var row = new Buffer('rowTest').toString('hex');
pool.cql("SELECT * FROM '%s' WHERE KEY = '%s'", ['cfTest',row], function(err, results){
  console.log('CQL RESULTS : ');
  console.log(err, results);
});
```

---

**Comment by devdazed** [comment]
it depends on your use case.  if you are only ever storing utf8 then make it a utf8 column.  BytesType is for binary data.

**Comment by Philmod** [comment]
How can I modify these options with helenus?

keyspace.createColumnFamily('cfTestName', function(err) { })

2012/3/9 Russ Bradberry <
reply@reply.github.com

> it depends on your use case.  if you are only ever storing utf8 then make
> it a utf8 column.  BytesType is for binary data.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/simplereach/helenus/issues/6#issuecomment-4422318

## 

_Philippe Modard_
+32 497 27 64 54
philippe.modard@gmail.com philippe.modard@modygo.com
twitter.com/philmod
re.vu/philippemodard
www.linkedin.com/in/philippemodard

**Comment by devdazed** [comment]
```
var options = {
  key_validateion_class: 'UTF8Type'
};

keyspace.createColumnFamily('cfTestName', options, function(err){ })
```

I am going to work on the docs a bit, but if you want some examples of things, check out the tests.
