### ISSUE TITLE
List of rows in a CF

### ISSUE THREAD

**Issue by Philmod** [simplereach/helenus#64]
Hello,

Is it possible to have the list of all the rows in a column family, in the Thrift style?

Thank you so much!!
Phil

**Comment by devdazed** [comment]
Unfortunately not, This isn't possible to do unless you are on the OrderedPartitioner and know the start and end key.  There is currently no place where keys are listed. Also, I don't see this as a function of a driver.  

As a side note, if you are using the random partitioner then CQL will not return proper results when doing key ranges.
