### ISSUE TITLE
RangeSlicesQuery

### ISSUE THREAD

**Issue by Philmod** [simplereach/helenus#8]
Hi,

how is it possible to do a RangeSlicesQuery?

Regards,
Philippe

**Comment by devdazed** [comment]
Currently I have not implemented RangeSlices, the main reason is that not many people use the OrderedPartitioner and Range Slices are not supported when you use the default RandomPartitioner.  If this is something you would like seen, we can work on getting it in on the next release.  

Helenus does, however, support column slicing via the `cf.get` command.
