### ISSUE TITLE
Is there a way to check if a row has a tombstone flag (has been deleted)?

### ISSUE THREAD

**Issue by rolandpoulter** [simplereach/helenus#86]

**Comment by calvinfo** [comment]
I check for `row.count !== 0`. If it has zero columns then chances are good it's deleted.

**Comment by devdazed** [comment]
AFAIK Tombstones don't come back in CQL3.   But I may be mistaken.  If that is the case, then there is no real way to tell if a tombstone has been removed.

If you aren't using CQL and, the entire row that has been removed then `row.count === 0` will tell you. But it could also mean the row has never existed.
