### ISSUE TITLE
Inserting blob value with CQL 3.

### ISSUE THREAD

**Issue by KhoaVo** [simplereach/helenus#87]
Is there a way to insert a binary value in to Casandra using cql?

I amusing 

conn.cql("insert into reportCache (key,data,dataBin) VALUES (?,?,?)",[cacheKey,ret,zipped]);

key and data are defined as text
and dataBin is defined as blob.

key is set as the primary.

cacheKey is a string,
ret is a string
zipped is a Buffer object.

I keep getting the error
HelenusInvalidRequestException
mismatched character '0' expecting '-'

Any ideas?

**Comment by devdazed** [comment]
what is the schema for the CF?

**Comment by KhoaVo** [comment]
CREATE TABLE reportcache (
  "key" text PRIMARY KEY,
  data text,
  databin blob
) ;

**Comment by devdazed** [comment]
Interesting, it should work.  I won't be able to look into this until next week as we are affected by the hurricane. In the meantime, you can do this:

``` js
conn.cql("insert into reportCache (key,data,dataBin) VALUES (?,?,?)",[cacheKey,ret,zipped.toString('hex')]);
```

**Comment by KhoaVo** [comment]
That worked thanks!

**Comment by alanristic** [comment]
Russ, anything new with this issue? buffer.toString('hex') works fine, but it takes 1x more space in disk. Any plans maybe?

Tnx, Alan

**Comment by devdazed** [comment]
why would it take more space on disk?  The hex gets converted to binary once it hits the C\* servers. Also, we are currently re-working the way CQL is done, there are a few issues with backward compatibility that make fixing this difficult.

**Comment by alanristic** [comment]
Russ tnx for quick reply. I mixed something in my dev code. You are right with your statement. Tnx & happy hacking ;)
