### ISSUE TITLE
Switch to original node-thrift

### ISSUE THREAD

**Issue by chris-rock** [simplereach/helenus#90]
I am not yet fully aware about the impact, but does it make sense to switch to https://npmjs.org/package/node-thrift? This package is also used by elasticsearch node client.

I just did a quick try and it does not seem to break anything. I can pull my changes if you like.

**Comment by devdazed** [comment]
Currently C\* Uses Thrift 0.7, and I believe that one is for Thrift 1.0-pre.  The version I forked was form the original 0.7 node-thrift that is no longer maintained. The forked version has several bug fixes and performance fixes as well.  Until C\* moves to a more recent version of Thrift, we should really stay on this driver.  

That being said, I haven't tried it and if all tests pass and it passes a simple stress test, we may be able to migrate over to it.

**Comment by chris-rock** [comment]
okay, just tested this further... works with most types, but date parsing is not working in node-thrift. therefore we should not switch at the moment.

**Comment by devdazed** [comment]
As we have seen from the previous pull requests, it is a bit too early to jump to the latest version of thrift.
