### ISSUE TITLE
Weird problem when describing keyspace

### ISSUE THREAD

**Issue by richtera** [simplereach/helenus#95]
When I create a column family with create table executing describe keyspace seems to work fine. But if I execute alter table all describe keyspace function calls no longer return any column families. It seems to work fine when using cqlsh but not within helenus. However I was unable to figure out where the breakage is. Has anyone ever seen this?

**Comment by devdazed** [comment]
This could be that the describe_keyspace calls may be cached. I'll have to dig a little deeper to find it.

**Comment by richtera** [comment]
I change my fork of cassandra-orm to use the system keyspace. It seems the
describe keyspace stuff doesn't return some of the cql3 generated tables
Thanks
Andy

On Mar 26, 2013, at 9:45 AM, Russ Bradberry notifications@github.com
wrote:

This could be that the describe_keyspace calls may be cached. I'll have to
dig a little deeper to find it.

—
Reply to this email directly or view it on
GitHubhttps://github.com/simplereach/helenus/issues/95#issuecomment-15458745
.

**Comment by devdazed** [comment]
This is by design and as a result of incompatibility between CQL3 and the Thrift client.  See the comments at: https://issues.apache.org/jira/browse/CASSANDRA-4924

There isn't anything I can really do about it as it is hidden from the client.
